"""Parity: behavioural compatibility verification for software migrations."""

from parity._version import __version__
from parity.api import check, verify
from parity.compatibility import (
    BudgetCaptureResult,
    approve_compatibility_finding,
    capture_compatibility_budget,
    load_compatibility_budget,
)
from parity.distilled import (
    ContractRetirement,
    DistillationResult,
    DistilledContractManifest,
    RetirementResult,
    distill_contract,
    retire_contract,
    verify_contract,
)
from parity.evidence import EvidenceResult, verify_evidence
from parity.invocation import FrameSequence, Invocation
from parity.migration import (
    MigrationManifest,
    MigrationResult,
    MigrationUnit,
    check_migration,
)
from parity.models import (
    AdapterName,
    Cardinality,
    CaseConfig,
    CaseProvenance,
    CaseResult,
    ComparisonOverride,
    ComparisonPolicy,
    CompatibilityBudget,
    CompatibilityDecision,
    CompatibilityFinding,
    CompatibilityResult,
    EqualRowCount,
    ForeignKey,
    FrameArgument,
    FrameConstraint,
    FrameSchema,
    FrameSequenceArgument,
    InvocationConfig,
    JsonArgument,
    KeyOverlap,
    KeyRef,
    PandasInput,
    ParityConfig,
    Relationship,
    RowComparison,
    SortedBy,
    SuiteProvenance,
    SuiteResult,
)
from parity.provenance import DistributionProvenance, RuntimeProvenance

__all__ = [
    "AdapterName",
    "BudgetCaptureResult",
    "Cardinality",
    "CaseConfig",
    "CaseProvenance",
    "CaseResult",
    "ComparisonOverride",
    "ComparisonPolicy",
    "CompatibilityBudget",
    "CompatibilityDecision",
    "CompatibilityFinding",
    "CompatibilityResult",
    "ContractRetirement",
    "DistillationResult",
    "DistilledContractManifest",
    "DistributionProvenance",
    "EqualRowCount",
    "EvidenceResult",
    "ForeignKey",
    "FrameArgument",
    "FrameConstraint",
    "FrameSchema",
    "FrameSequence",
    "FrameSequenceArgument",
    "Invocation",
    "InvocationConfig",
    "JsonArgument",
    "KeyOverlap",
    "KeyRef",
    "MigrationManifest",
    "MigrationResult",
    "MigrationUnit",
    "PandasInput",
    "ParityConfig",
    "Relationship",
    "RetirementResult",
    "RowComparison",
    "RuntimeProvenance",
    "SortedBy",
    "SuiteProvenance",
    "SuiteResult",
    "__version__",
    "approve_compatibility_finding",
    "capture_compatibility_budget",
    "check",
    "check_migration",
    "distill_contract",
    "load_compatibility_budget",
    "retire_contract",
    "verify",
    "verify_contract",
    "verify_evidence",
]
