"""Parity: semantic verification for dataframe migrations."""

from parity._version import __version__
from parity.api import check, verify
from parity.distilled import (
    DistillationResult,
    DistilledContractManifest,
    distill_contract,
    verify_contract,
)
from parity.evidence import EvidenceResult, verify_evidence
from parity.migration import (
    MigrationManifest,
    MigrationResult,
    MigrationUnit,
    check_migration,
)
from parity.models import (
    AdapterName,
    Cardinality,
    CaseConfig,
    CaseProvenance,
    CaseResult,
    ComparisonPolicy,
    EqualRowCount,
    ForeignKey,
    FrameConstraint,
    FrameSchema,
    InputBundle,
    InputSpec,
    KeyOverlap,
    KeyRef,
    PandasInput,
    ParityConfig,
    Relationship,
    RowComparison,
    SortedBy,
    SuiteProvenance,
    SuiteResult,
)
from parity.provenance import DistributionProvenance, RuntimeProvenance

__all__ = [
    "AdapterName",
    "Cardinality",
    "CaseConfig",
    "CaseProvenance",
    "CaseResult",
    "ComparisonPolicy",
    "DistillationResult",
    "DistilledContractManifest",
    "DistributionProvenance",
    "EqualRowCount",
    "EvidenceResult",
    "ForeignKey",
    "FrameConstraint",
    "FrameSchema",
    "InputBundle",
    "InputSpec",
    "KeyOverlap",
    "KeyRef",
    "MigrationManifest",
    "MigrationResult",
    "MigrationUnit",
    "PandasInput",
    "ParityConfig",
    "Relationship",
    "RowComparison",
    "RuntimeProvenance",
    "SortedBy",
    "SuiteProvenance",
    "SuiteResult",
    "__version__",
    "check",
    "check_migration",
    "distill_contract",
    "verify",
    "verify_contract",
    "verify_evidence",
]
