"""Original configuration templates for Parity projects."""

from __future__ import annotations

import json
import os
import re
import tempfile
from collections.abc import Sequence
from pathlib import Path

from parity.provenance import normalize_distribution_names
from parity.targets import is_import_target

_CASE_NAME = re.compile(r"^[A-Za-z0-9_.-]+$")
_ADAPTERS = frozenset({"auto", "pandas", "polars", "arrow"})


def _lexists(path: Path) -> bool:
    """Return whether a directory entry exists, including dangling symlinks."""

    return os.path.lexists(path)


def _validate_replaceable_destination(path: Path) -> None:
    """Reject directory and special-file destinations before any forced write."""

    if _lexists(path) and not (path.is_file() or path.is_symlink()):
        raise ValueError(f"destination is not a replaceable file or symlink: {path}")


def _validate_target(label: str, target: str) -> None:
    if not is_import_target(target):
        raise ValueError(f"{label} must be an import target such as package.module:function")


def _validate_case_name(case_name: str) -> None:
    if not _CASE_NAME.fullmatch(case_name):
        raise ValueError("case_name may contain only letters, numbers, dot, underscore and hyphen")


def _validate_adapter(label: str, adapter: str) -> None:
    if adapter not in _ADAPTERS:
        choices = ", ".join(sorted(_ADAPTERS))
        raise ValueError(f"{label} must be one of: {choices}")


def _toml_string(value: str) -> str:
    """Render a TOML basic string using JSON's compatible escaping rules."""

    return json.dumps(value, ensure_ascii=False)


def _toml_array(values: Sequence[str]) -> str:
    return "[" + ", ".join(_toml_string(value) for value in values) + "]"


def _atomic_write_text(destination: Path, content: str, *, force: bool) -> None:
    """Publish one complete file without racing the no-overwrite contract."""

    destination.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{destination.name}.", suffix=".tmp", dir=destination.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        if force:
            os.replace(temporary, destination)
        else:
            # A hard link atomically publishes the fully-written inode only
            # when destination is absent. Concurrent creators cannot replace
            # one another between a preflight exists() check and publication.
            try:
                os.link(temporary, destination)
            except FileExistsError:
                raise FileExistsError(
                    f"refusing to overwrite existing configuration: {destination}"
                ) from None
            temporary.unlink()
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def _relative_config_path(source: Path, config_path: Path) -> str:
    """Return a path that remains valid when resolved beside the generated config."""

    relative = os.path.relpath(source.resolve(), config_path.parent.resolve())
    return Path(relative).as_posix()


def _relative_python_path(source: Path, config_path: Path) -> str:
    """Anchor a Python launch path without dereferencing a virtualenv symlink."""

    relative = os.path.relpath(
        Path(os.path.abspath(source)),
        config_path.parent.resolve(),
    )
    return Path(relative).as_posix()


def render_config_template(
    *,
    reference: str = "parity_example:reference",
    candidate: str = "parity_example:candidate",
    case_name: str = "orders",
) -> str:
    """Render a documented ``parity.toml`` suitable for immediate editing.

    Values are validated before interpolation so this helper never needs a TOML
    escaping implementation. It deliberately accepts import targets and case names
    only, rather than arbitrary TOML strings.
    """

    for label, target in (("reference", reference), ("candidate", candidate)):
        _validate_target(label, target)
    _validate_case_name(case_name)

    return f'''# parity.toml — generated by Parity
# Paths are resolved relative to this file, not the current shell directory.
version = 1
artifact_dir = ".parity"
fail_fast = false

[[cases]]
name = "{case_name}"
timeout_seconds = 30
tags = ["migration", "critical"]

[cases.reference]
target = "{reference}"
adapter = "pandas"
pandas_input = "arrow"
record_distributions = []

[cases.candidate]
target = "{candidate}"
adapter = "polars"
pandas_input = "arrow"
record_distributions = []

# A case needs a fixture, a generated schema, or both. This generated schema
# deliberately includes nulls, signed values and floating-point edge cases.
[cases.schema]
min_rows = 0
max_rows = 40
unique_together = []
constraints = []

[[cases.schema.columns]]
name = "quantity"
dtype = "int64"
nullable = true
minimum = -1000000
maximum = 1000000
examples = [-1, 0, 1, 127, 128]

[[cases.schema.columns]]
name = "unit_price"
dtype = "float64"
nullable = true
minimum = -1000000.0
maximum = 1000000.0
examples = [0.0, -0.0, 0.1]

[cases.comparison]
column_order = "strict"
row_order = "ignore"
row_keys = []
dtype = "compatible"
names = "strict"
null_equal = true
nan_equal = true
null_nan_equal = false
signed_zero_equal = true
check_exceptions = true
check_input_mutation = true
rtol = 1e-7
atol = 0.0
datetime_tolerance_ns = 0
ignored_columns = []

[cases.generation]
max_examples = 250
max_findings = 10
stability_repeats = 2
search = true
seed = 20260813
adversarial_examples = true
shrink = true
derandomize = false
suppress_too_slow = true

[cases.performance]
enabled = true
warmups = 1
repeats = 9
max_slowdown = 1.25
max_memory_ratio = 1.5
min_reference_ms = 1.0
fail_on_regression = false

# To seed generation from a non-sensitive real sample, add this case-level key
# immediately below `tags` above:
# fixture = "tests/fixtures/orders.parquet"
'''


def write_config_template(
    path: str | Path = "parity.toml",
    *,
    force: bool = False,
    reference: str = "parity_example:reference",
    candidate: str = "parity_example:candidate",
    case_name: str = "orders",
) -> Path:
    """Write a generated configuration without silently replacing user work."""

    destination = Path(path)
    if _lexists(destination) and not force:
        raise FileExistsError(f"refusing to overwrite existing configuration: {destination}")
    if force:
        _validate_replaceable_destination(destination)
    _atomic_write_text(
        destination,
        render_config_template(
            reference=reference,
            candidate=candidate,
            case_name=case_name,
        ),
        force=force,
    )
    return destination


def render_project_config(
    *,
    reference: str,
    candidate: str,
    fixture: str,
    case_name: str = "migration",
    reference_adapter: str = "auto",
    candidate_adapter: str = "auto",
    reference_python: str | None = None,
    candidate_python: str | None = None,
    workdir: str | None = None,
    record_distributions: Sequence[str] = (),
    row_keys: Sequence[str] = (),
) -> str:
    """Render one minimal, fixture-backed project configuration."""

    for label, target in (("reference", reference), ("candidate", candidate)):
        _validate_target(label, target)
    _validate_case_name(case_name)
    _validate_adapter("reference_adapter", reference_adapter)
    _validate_adapter("candidate_adapter", candidate_adapter)
    if not fixture:
        raise ValueError("fixture path cannot be empty")
    distributions = normalize_distribution_names(record_distributions)
    if any(not key for key in row_keys):
        raise ValueError("row keys cannot be empty")
    if len(row_keys) != len(set(row_keys)):
        raise ValueError("row keys must be unique")

    lines = [
        "# parity.toml — generated by Parity",
        "# Paths are resolved relative to this file, not the current shell directory.",
        "version = 1",
        'artifact_dir = ".parity"',
        "",
        "[[cases]]",
        f"name = {_toml_string(case_name)}",
        f"fixture = {_toml_string(fixture)}",
        "",
        "[cases.reference]",
        f"target = {_toml_string(reference)}",
    ]
    if reference_adapter != "auto":
        lines.append(f"adapter = {_toml_string(reference_adapter)}")
    if reference_python is not None:
        lines.append(f"python = {_toml_string(reference_python)}")
    if workdir is not None:
        lines.append(f"workdir = {_toml_string(workdir)}")
    if distributions:
        lines.append(f"record_distributions = {_toml_array(distributions)}")

    lines.extend(
        [
            "",
            "[cases.candidate]",
            f"target = {_toml_string(candidate)}",
        ]
    )
    if candidate_adapter != "auto":
        lines.append(f"adapter = {_toml_string(candidate_adapter)}")
    if candidate_python is not None:
        lines.append(f"python = {_toml_string(candidate_python)}")
    if workdir is not None:
        lines.append(f"workdir = {_toml_string(workdir)}")
    if distributions:
        lines.append(f"record_distributions = {_toml_array(distributions)}")
    if row_keys:
        lines.extend(
            [
                "",
                "[cases.comparison]",
                'row_order = "keyed"',
                f"row_keys = {_toml_array(row_keys)}",
            ]
        )
    lines.append("")
    return "\n".join(lines)


def write_project_config(
    path: str | Path,
    *,
    reference: str,
    candidate: str,
    fixture: str | Path,
    case_name: str = "migration",
    reference_adapter: str = "auto",
    candidate_adapter: str = "auto",
    reference_python: str | Path | None = None,
    candidate_python: str | Path | None = None,
    target_workdir: str | Path | None = None,
    record_distributions: Sequence[str] = (),
    row_keys: Sequence[str] = (),
    force: bool = False,
) -> Path:
    """Validate and atomically write a runnable project configuration."""

    from parity.adapters import load_fixture

    destination = Path(path)
    if _lexists(destination) and not force:
        raise FileExistsError(f"refusing to overwrite existing configuration: {destination}")
    if force:
        _validate_replaceable_destination(destination)

    fixture_path = Path(fixture)
    load_fixture(fixture_path)
    python_paths: dict[str, Path | None] = {
        "reference": Path(reference_python) if reference_python is not None else None,
        "candidate": Path(candidate_python) if candidate_python is not None else None,
    }
    for label, python_path in python_paths.items():
        if python_path is not None and not python_path.is_file():
            raise ValueError(f"{label} Python executable is not a file")
        if os.name != "nt" and python_path is not None and not os.access(python_path, os.X_OK):
            raise ValueError(f"{label} Python executable is not executable")

    effective_workdir = Path.cwd() if target_workdir is None else Path(target_workdir)
    content = render_project_config(
        reference=reference,
        candidate=candidate,
        fixture=_relative_config_path(fixture_path, destination),
        case_name=case_name,
        reference_adapter=reference_adapter,
        candidate_adapter=candidate_adapter,
        reference_python=(
            _relative_python_path(python_paths["reference"], destination)
            if python_paths["reference"] is not None
            else None
        ),
        candidate_python=(
            _relative_python_path(python_paths["candidate"], destination)
            if python_paths["candidate"] is not None
            else None
        ),
        workdir=(
            _relative_config_path(effective_workdir, destination)
            if effective_workdir.resolve() != destination.parent.resolve()
            else None
        ),
        record_distributions=record_distributions,
        row_keys=row_keys,
    )
    _atomic_write_text(destination, content, force=force)
    return destination


def render_example_module() -> str:
    """Return the small, passing pandas-to-Polars example used by ``parity init``."""

    return '''"""Generated Parity example. Replace these functions with your migration."""

import pandas as pd
import polars as pl


def reference(frame: pd.DataFrame) -> pd.DataFrame:
    """Existing implementation: total value with a documented float contract."""

    result = frame.astype({"quantity": "float64", "unit_price": "float64"})
    result["total"] = result["quantity"] * result["unit_price"]
    return result[["quantity", "unit_price", "total"]]


def candidate(frame: pl.DataFrame) -> pl.DataFrame:
    """Rewritten implementation with explicit cross-engine missing values."""

    normalized = frame.with_columns(
        pl.col("quantity").cast(pl.Float64).fill_null(float("nan")),
        pl.col("unit_price").cast(pl.Float64).fill_null(float("nan")),
    )
    return normalized.with_columns(
        (pl.col("quantity") * pl.col("unit_price")).alias("total")
    ).select("quantity", "unit_price", "total")
'''


def write_starter(path: str | Path = "parity.toml", *, force: bool = False) -> list[Path]:
    """Create a runnable configuration and implementation pair for ``parity init``."""

    config_path = Path(path)
    example_path = config_path.parent / "parity_example.py"
    existing = [item for item in (config_path, example_path) if _lexists(item)]
    if existing and not force:
        raise FileExistsError(f"refusing to overwrite existing file: {existing[0]}")
    if force:
        for item in (config_path, example_path):
            _validate_replaceable_destination(item)
    _atomic_write_text(config_path, render_config_template(), force=force)
    _atomic_write_text(example_path, render_example_module(), force=force)
    return [config_path, example_path]


__all__ = [
    "render_config_template",
    "render_example_module",
    "render_project_config",
    "write_config_template",
    "write_project_config",
    "write_starter",
]
