"""Original, dependency-free configuration templates for Parity projects."""

from __future__ import annotations

import re
from pathlib import Path

_TARGET = re.compile(r"^[A-Za-z_][\w.]*:[A-Za-z_][\w.]*$")
_CASE_NAME = re.compile(r"^[A-Za-z0-9_.-]+$")


def render_config_template(
    *,
    reference: str = "parity_example:reference",
    candidate: str = "parity_example:candidate",
    case_name: str = "orders",
) -> str:
    """Render a documented ``parity.toml`` suitable for immediate editing.

    Values are validated before interpolation so this helper never needs a TOML
    escaping implementation. It deliberately accepts import targets and case names
    only, rather than arbitrary TOML strings.
    """

    for label, target in (("reference", reference), ("candidate", candidate)):
        if not _TARGET.fullmatch(target):
            raise ValueError(f"{label} must be an import target such as package.module:function")
    if not _CASE_NAME.fullmatch(case_name):
        raise ValueError("case_name may contain only letters, numbers, dot, underscore and hyphen")

    return f'''# parity.toml — generated by Parity
# Paths are resolved relative to this file, not the current shell directory.
version = 1
artifact_dir = ".parity"
fail_fast = false

[[cases]]
name = "{case_name}"
timeout_seconds = 30
tags = ["migration", "critical"]

[cases.reference]
target = "{reference}"
adapter = "pandas"
pandas_input = "arrow"
record_distributions = []

[cases.candidate]
target = "{candidate}"
adapter = "polars"
pandas_input = "arrow"
record_distributions = []

# A case needs a fixture, a generated schema, or both. This generated schema
# deliberately includes nulls, signed values and floating-point edge cases.
[cases.schema]
min_rows = 0
max_rows = 40
unique_together = []
constraints = []

[[cases.schema.columns]]
name = "quantity"
dtype = "int64"
nullable = true
minimum = -1000000
maximum = 1000000
examples = [-1, 0, 1, 127, 128]

[[cases.schema.columns]]
name = "unit_price"
dtype = "float64"
nullable = true
minimum = -1000000.0
maximum = 1000000.0
examples = [0.0, -0.0, 0.1]

[cases.comparison]
column_order = "strict"
row_order = "ignore"
row_keys = []
dtype = "compatible"
names = "strict"
null_equal = true
nan_equal = true
null_nan_equal = false
signed_zero_equal = true
check_exceptions = true
check_input_mutation = true
rtol = 1e-7
atol = 0.0
datetime_tolerance_ns = 0
ignored_columns = []

[cases.generation]
max_examples = 250
max_findings = 1
stability_repeats = 2
seed = 20260813
adversarial_examples = true
shrink = true
derandomize = false
suppress_too_slow = true

[cases.performance]
enabled = true
warmups = 1
repeats = 5
max_slowdown = 1.25
max_memory_ratio = 1.5
min_reference_ms = 1.0
fail_on_regression = false

# To seed generation from a non-sensitive real sample, add this case-level key
# immediately below `tags` above:
# fixture = "tests/fixtures/orders.parquet"
'''


def write_config_template(
    path: str | Path = "parity.toml",
    *,
    force: bool = False,
    reference: str = "parity_example:reference",
    candidate: str = "parity_example:candidate",
    case_name: str = "orders",
) -> Path:
    """Write a generated configuration without silently replacing user work."""

    destination = Path(path)
    if destination.exists() and not force:
        raise FileExistsError(f"refusing to overwrite existing configuration: {destination}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        render_config_template(
            reference=reference,
            candidate=candidate,
            case_name=case_name,
        ),
        encoding="utf-8",
    )
    return destination


def render_example_module() -> str:
    """Return the small, passing pandas-to-Polars example used by ``parity init``."""

    return '''"""Generated Parity example. Replace these functions with your migration."""

import pandas as pd
import polars as pl


def reference(frame: pd.DataFrame) -> pd.DataFrame:
    """Existing implementation: total value with a documented float contract."""

    result = frame.astype({"quantity": "float64", "unit_price": "float64"})
    result["total"] = result["quantity"] * result["unit_price"]
    return result[["quantity", "unit_price", "total"]]


def candidate(frame: pl.DataFrame) -> pl.DataFrame:
    """Rewritten implementation with explicit cross-engine missing values."""

    normalized = frame.with_columns(
        pl.col("quantity").cast(pl.Float64).fill_null(float("nan")),
        pl.col("unit_price").cast(pl.Float64).fill_null(float("nan")),
    )
    return normalized.with_columns(
        (pl.col("quantity") * pl.col("unit_price")).alias("total")
    ).select("quantity", "unit_price", "total")
'''


def write_starter(path: str | Path = "parity.toml", *, force: bool = False) -> list[Path]:
    """Create a runnable configuration and implementation pair for ``parity init``."""

    config_path = Path(path)
    example_path = config_path.parent / "parity_example.py"
    existing = [item for item in (config_path, example_path) if item.exists()]
    if existing and not force:
        raise FileExistsError(f"refusing to overwrite existing file: {existing[0]}")
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(render_config_template(), encoding="utf-8")
    example_path.write_text(render_example_module(), encoding="utf-8")
    return [config_path, example_path]


__all__ = [
    "render_config_template",
    "render_example_module",
    "write_config_template",
    "write_starter",
]
